### ISSUE TITLE
Parsing the values string failed.

### ISSUE THREAD

**Issue by worldworm** [bobey/storj-collectd-plugin#8]
Hi there,

As soon as everything is installed as described, my /var/log/syslog is getting spammed

collectd[562]: parse_value: Failed to parse string as gauge: "...".
collectd[562]: -1 Parsing the values string failed.

Description:    Ubuntu 17.04
Release:        17.04
Codename:       zesty

**Comment by worldworm** [comment]
ok i think it's happening cause my share is new and the space is not initialized yet

**Comment by phobeus81** [comment]
Why is this issue closed? I consider it still a bug, if a node that not having a connection is returning a string instead of an integer. I would expect that 0 is returned instead.
